Solution
mate-academy/react_static-list-of-todos-js pull request #188
Opened 2023-08-15 11:22 UTC by YuriyBilskiy

[DEMO LINK](https://yuriybilskiy.github.io/react_static-list-of-todos-js/)

2023-08-15 13:19 UTC, VitaliyBodnar requested changes

2023-08-15 13:19 UTC, VitaliyBodnar commented on src/components/TodoInfo/TodoInfo.jsx
> +    <article className={`TodoInfo TodoInfo--${completed ? 'completed' : ''}`}>
it's better to use classname library for making dynamic classname

2023-08-16 07:55 UTC, DarkMistyRoom requested changes
Good! One fix is needed

2023-08-16 07:55 UTC, DarkMistyRoom commented on src/components/TodoInfo/TodoInfo.jsx
> +      <UserInfo user={user} />
don't render UserInfo if the is no user

2023-08-16 12:41 UTC, IvanFesenko approved these changes
well done

2024-08-07 15:35 UTC, closed without merging