create simple to-do app
mate-academy/react_static-list-of-todos-js pull request #284
Opened 2023-09-07 08:56 UTC by OPTIMISTIXX

(https://OPTIMISTIXX.github.io/react_static-list-of-todos-js/)

2023-09-07 09:13 UTC, VitaliyBondarenko1982 requested changes
Good job.
Suggest some improvements.

2023-09-07 09:13 UTC, VitaliyBondarenko1982 commented on src/App.jsx
> +import { UserInfo } from './components/UserInfo';
looks like UserInfo not use in this module.
```suggestion
```
![Screenshot from 2023-09-07 12-07-55](https://github.com/mate-academy/react_static-list-of-todos-js/assets/33029864/ac5ae4a2-2792-4a7e-812b-2b29cbe88416)

2023-09-07 09:13 UTC, VitaliyBondarenko1982 commented on src/components/TodoList/TodoList.jsx
> +  </section>
```suggestion
  <ul className="TodoList">
    {todos.map(todo => (
      <TodoInfo key={todo.id} todo={todo} />
    ))}
  </ul>
```
use `li` in TodoInfo instead `article`
and `li` shoul be in `ul` or ol tag (for this case `ul`).
also reset default styles for list
set `list-style: none` for .TodoList, also ul has other default styles which should be resetted (margin, padding...)

2023-09-08 10:08 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2023-09-08 10:08 UTC, volodymyr-soltys97 commented on src/components/TodoInfo/TodoInfo.jsx
> +  <li className={cn('TodoInfo', {
You can use a destructuring for `todo`

2023-09-08 10:08 UTC, volodymyr-soltys97 commented on src/components/TodoInfo/TodoInfo.jsx
> +    'TodoInfo--completed': todo.completed === true,
```suggestion
    'TodoInfo--completed': todo.completed,
```

2023-09-08 10:08 UTC, volodymyr-soltys97 commented on src/components/UserInfo/UserInfo.jsx
> +  </a>
If there is no user, the link to the email will not work for you, you need to add checks, you can also use destructuring for the user

2023-09-08 10:59 UTC, volodymyr-soltys97 requested changes

2023-09-08 10:59 UTC, volodymyr-soltys97 commented on src/components/UserInfo/UserInfo.jsx
> +      )}
```suggestion
    <>
      {user && (
        <a className="UserInfo" href={`mailto:${email}`}>
          {name}
        </a>
      )}
```

2023-09-09 07:45 UTC, nazarmatsevych approved these changes
👍

2025-08-04 16:12 UTC, closed without merging