Solution
mate-academy/react_static-list-of-todos-js pull request #41
Opened 2023-06-29 15:11 UTC by eleonora-demikh

[DEMO LINK](https://eleonora-demikh.github.io/react_static-list-of-todos-js/)

2023-06-29 17:28 UTC, FlameInBrains approved these changes
Well-done!

2023-06-30 06:29 UTC, tetiana-ivanchenko requested changes

2023-06-30 06:29 UTC, tetiana-ivanchenko commented on src/components/TodoInfo/TodoInfo.jsx
> +    className={`TodoInfo ${todo.completed ? 'TodoInfo--completed' : ''}`}
use classname library

2023-06-30 06:29 UTC, tetiana-ivanchenko commented on src/components/TodoInfo/TodoInfo.jsx
> +      {todo.title}
use destructure assign

2023-06-30 06:29 UTC, tetiana-ivanchenko commented on src/components/UserInfo/UserInfo.jsx
> +  <a className="UserInfo" href={`mailto:${user.email}`}>
use destructure assign

2023-06-30 07:33 UTC, tetiana-ivanchenko approved these changes

2025-01-10 08:24 UTC, closed without merging